### ISSUE TITLE
requirements.txt uvicorn 오탈자 수정 관련

### ISSUE THREAD

**Issue by sihyeong671** [OIDC2023-SilverLining/monibot#17]
[code line](https://github.com/OIDC2023-SilverLining/monibot/blob/c79c1cbf8d4d1ea77ba7d558652869841a2aa5db/src/gptCache/requirements.txt#L12C14-L12C14)에uvicorn[standart]로 되어있는데 큰 오류가 없어서 의문인데 uvicorn[standard]로 수정이 필요할까요?

**Comment by sejongk** [comment]
@sihyeong671 넵 수정 부탁드려요!
